
[General]
	#Which energy system should be used with XyCraft related machines.
	#Allowed Values: Xynergy, ForgeEnergy
	energy_paradigm = "Xynergy"

[BasicMachines]
	#Allow the Water Block to fill a fluid container with water
	water_block_fills_container = true
	#Allow the Fluid Void to empty a fluid container
	fluid_void_empties_container = true
	#How many planters in a line are allowed to accelerate a plant growth
	#Range: 1 ~ 128
	planter_limit = 16
	#How frequently does the Fabricator try to craft its recipe in ticks.
	#Range: 5 ~ 200
	fabricator_craft_frequency = 10
	#How frequently does the Extractor try to revalidate its recipe in ticks.
	#Range: 5 ~ 200
	extractor_revalidate_frequency = 10
	#How far a player may fly before severing the connection of the Balloon on a stick. Note, this is not a sphere.
	#Range: 3 ~ 32
	balloon_on_a_stick_radius = 9
	#How large of a radius should the player be able to fly around a hover pylon
	#Range: 8 ~ 64
	hover_pylon_range = 16
	#How large of a radius should the collector be allowed to pick up items
	#Range: 1 ~ 64
	collector_pickup_range = 3

	[BasicMachines.LightField]
		#How Large of a radius should spawns be prevented
		#Range: 4 ~ 128
		light_field_range = 24
		#Determines if a light field block can prevent a siege from occurring.
		light_field_siege_prevention = true
		#Determines if a light field block can prevent endermen from warping to within the field range.
		light_field_ender_warp_prevention = true

	#How much can a void container pull at once. Note, this is only how much it can draw itself, anything pushed to it will be voided immediately still!
	[BasicMachines.HydroPump]
		#How frequently a cycle happens in ticks
		#Range: 5 ~ 1200
		hydro_pump_process_frequency = 10
		#How much fluid can the hydro pump push in a single cycle in milli-buckets
		#Range: > 0
		hydro_pump_fluid_push_amount = 100
		#How much fluid can an external source pull in milli-buckets
		#Range: > 0
		hydro_pump_fluid_external_pull_amount = 1000000000

	[BasicMachines.VoidContainment]
		#How frequently a cycle happens in ticks
		#Range: 5 ~ 1200
		void_containment_process_frequency = 10
		#How many items can the void containment pull in a single process
		#Range: 0 ~ 576
		void_containment_item_pull_amount = 8
		#How much fluid can the void containment pull in a single process in milli-buckets
		#Range: 0 ~ 1000
		void_containment_fluid_pull_amount = 100
		#How much forge energy can the void containment pull in a single process
		#Range: > 0
		void_containment_power_pull_amount = 100

	#How much can a Creative Selector create. note, this is only how much it can push, anything pulling can pull as much as it desires!
	[BasicMachines.Selector]
		#How frequently a cycle happens in ticks
		#Range: 5 ~ 1200
		selector_process_frequency = 5
		#How many items can the selector push per cycle
		#Range: 1 ~ 576
		selector_item_amount = 64
		#How much fluid can the selector push per cycle in milli-buckets
		#Range: 1 ~ 1000000000
		selector_fluid_amount = 1000000000
		#How much forge energy can the selector push per cycle
		#Range: > 1
		selector_energy_amount = 16000

[MultiBlocks]

	#Cuboid fluid storage.
	[MultiBlocks.Tank]
		#Maximum dimensions of a tank. A single dimension is measured from wall to wall (inclusive).
		#Range: 3 ~ 33
		tank_size_limit = 13
		#How much fluid can be stored for each empty air block in the defined box. Measured in milli-buckets (mB)
		#Range: 1 ~ 64000
		tank_storage_per_block = 8000
		#How frequently a tank will tick.
		#Range: 5 ~ 20
		tank_tick_rate = 10

[EnergyContainers]

	[EnergyContainers.Duracell]
		#Power capacity
		#Range: > 1
		duracell_capacity = 1000
		#Extraction rate
		#Range: > 0
		duracell_extraction_rate = 20
		#Charge rate
		#Range: > 0
		duracell_receive_rate = 20

