
[ChunkGeneration]
	#Is ChunkByChunk generation enabled
	enabled = true
	#Should empty chunks be generated as bedrock
	seal_world = false
	#Should the nether start empty with chunks spawning in response to overworld spawns
	synch_nether_chunk_spawn = true
	#Should chunks include a chest with materials for generating further chunks?
	spawn_new_chunk_chest = true
	#Should the chest spawn in the initial chunk only?
	spawn_chest_in_initial_chunk_only = false
	#Should the generated chest be a bedrock chest
	use_bedrock_chest = false
	#The type of items the bedrock chest provides
	#Allowed Values: ChunkSpawner, Random, WorldCore, WorldCrystal, WorldFragment, WorldForge, UnstableChunkSpawner
	chest_contents = "Random"
	#The number of items the bedrock chest provides
	#Range: 1 ~ 64
	chest_quantity = 1
	#The minimum depth at which the chunk spawner chest can spawn
	#Range: -64 ~ 128
	min_chest_spawn_depth = -60
	#The maximum depth at which the chunk spawner chest can spawn
	#Range: -64 ~ 128
	max_chest_spawn_depth = -53
	#The number of chunks to spawn initially
	#Range: 0 ~ 100
	initial_chunks = 1
	#Whether to spawn a full strip of chunks along an axis
	spawn_chunk_strip = false
	#Number of chunk layers to spawn per tick
	#Range: 1 ~ 512
	chunk_layer_spawn_rate = 8

[Gameplay]
	#Can blocks be placed outside spawned chunks
	block_placement_allowed_outside_spawned_chunks = true
	#What restriction to place on starting location
	#Allowed Values: Biome, None, Village
	start_restriction = "Village"
	#The tag or name of the biome the starting spawn should be in (if not a village, blank for any
	starting_biome = #minecraft:is_forest
	#Prevent leaves spawned by the chunk spawners from decaying
	chunk_spawn_leaf_decay_disabled = false

[WorldForge]
	#The rate at which the world forge processes consumed blocks, in fuel per tick
	#Range: 1 ~ 256
	production_rate = 1
	#The value of fuel provided by soils (dirt, sand, gravel, etc). 0 to disallow use as fuel
	#Range: 0 ~ 256
	soil_fuel_value = 2
	#The value of fuel provided by raw stones (cobblestone, deep slate cobblestone, etc). 0 to disallow use as fuel
	#Range: 0 ~ 256
	stone_fuel_value = 4
	#The value of fuel provided by more valuable materials (none by default, this is for modpacks and extensions)
	#Range: 0 ~ 256
	strong_fuel_value = 8
	#The cost in fuel to produce a single world fragment
	#Range: 1 ~ 256
	fragment_fuel_cost = 32

[WorldScanner]
	#The amount of fuel provided by each world fragment (and then scaled up for world shard, crystal and core
	#Range: 1 ~ 512
	fuel_per_fragment = 32
	#The amount of fuel required to scan each chunk
	#Range: 1 ~ 65534
	fuel_required_per_chunk = 32
	#The amount of fuel consumed each tick
	#Range: 1 ~ 65534
	fuel_consumed_per_tick = 1

[WorldMender]
	#Ticks between chunk spawns per world mender (world menders will not spawn chunks if chunks are already being spawned)
	#Range: 1 ~ 72000
	cooldown = 1

[BedrockChest]
	#The number of blocks within the chunk above the bedrock chest allowed to remain before it will open
	#Range: 0 ~ 65534
	bedrock_chest_unlock_at_blocks_remaining = 16
