blank_issues_enabled: false
contact_links:
  - name: Ammonium Discord Server 
    url: https://discord.gg/hEaS5EVCH7
    about: discuss about all Mechanical Mastery modpacks
  - name: kc00l Discord server
    url: https://discord.gg/QHKjtFuG
    about: discuss about my mods and other modpacks
