
#General settings
[general]
	#When enabled causes water based liquid blocks to cause nausea when collided [default: true]
	liquidCausesNausea = true
	#When enabled causes water based liquid blocks to cause slowness when collided [default: true]
	liquidCausesSlowness = true
	#When enabled causes will try to make the liquid turn every bit into a block [default: true]
	completelyFill = true
	#Makes liquid netherrack have a 1 in X chance of drying with fire on top (0 = disabled) [default: 30]
	#Range: > 1
	netherrackFireChance = 30
	#Makes liquid ore have a 1 in X chance of drying into an ore block (higher = less chance) [default: 64]
	#Range: > 6
	oreChance = 64

#Crafting settings
[crafting]
	#Enable crafting buckets with ice [default: true]
	craftWithIce = true
	#Enable crafting buckets with a water bottle where applicable [default: true]
	craftWithWaterBottle = true
	#Enable crafting buckets with a bucket of the fitting liquid [default: true]
	craftWithWaterBucket = true
	#Enables the crafting of the Liquid Ore bucket [default: true]
	craftLiquidOre = true

