
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 914505
	#The name of the modpack
	modpackName = "Mechanical Master Plus"
	#The version of the modpack
	modpackVersion = "r1.1.2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

