
#Dimensional shard ore generation
[worldgen]

	#Overworld
	[worldgen.nether]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 8
		#Max height
		#Range: -512 ~ 512
		oreMax = 40
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 8
		#Min height
		#Range: -512 ~ 512
		oreMin = 2

	#End
	[worldgen.end]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 8
		#Max height
		#Range: -512 ~ 512
		oreMax = 80
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 10
		#Min height
		#Range: -512 ~ 512
		oreMin = 2

	#Overworld
	[worldgen.overworld]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 2
		#Max height
		#Range: -512 ~ 512
		oreMax = 40
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 5
		#Min height
		#Range: -512 ~ 512
		oreMin = 2

	#Other Dimensions
	[worldgen.dimensions]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 6
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 10
		#Min height
		#Range: -512 ~ 512
		oreMin = -15
		#Max height
		#Range: -512 ~ 512
		oreMax = 40

