
[World]

	[World.Ores]

		[World.Ores."Oil Sand"]
			#Whether this ore should spawn in the world.
			Enable = true

		[World.Ores.Apatite]
			#Whether this ore should spawn in the world.
			Enable = true

		[World.Ores.Silver]
			#Whether this ore should spawn in the world.
			Enable = true

		[World.Ores.Lead]
			#Whether this ore should spawn in the world.
			Enable = true

		[World.Ores.Nickel]
			#Whether this ore should spawn in the world.
			Enable = true

		[World.Ores.Cinnabar]
			#Whether this ore should spawn in the world.
			Enable = true

		[World.Ores.Sulfur]
			#Whether this ore should spawn in the world.
			Enable = true

		[World.Ores.Tin]
			#Whether this ore should spawn in the world.
			Enable = true

		[World.Ores.Niter]
			#Whether this ore should spawn in the world.
			Enable = true

