[Gem]
	#Color of the finder's name
	#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
	nameColor = "DARK_AQUA"
	#Length of the needle indicators
	#Range: 0.0 ~ 1.0
	needleLength = 0.35
	#Width of the needle indicators
	#Range: 0.0 ~ 1.0
	needleWidth = 0.1
	#Size of the arrow indicators
	#Range: 0.0 ~ 1.0
	arrowSize = 0.2
	#Draw an outline around each indicator for better visualization
	drawOutline = false

[Metal]
	#Color of the finder's name
	#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
	nameColor = "GOLD"
	#Length of the needle indicators
	#Range: 0.0 ~ 1.0
	needleLength = 0.35
	#Width of the needle indicators
	#Range: 0.0 ~ 1.0
	needleWidth = 0.1
	#Size of the arrow indicators
	#Range: 0.0 ~ 1.0
	arrowSize = 0.2
	#Draw an outline around each indicator for better visualization
	drawOutline = false

[Mineral]
	#Color of the finder's name
	#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
	nameColor = "DARK_PURPLE"
	#Length of the needle indicators
	#Range: 0.0 ~ 1.0
	needleLength = 0.35
	#Width of the needle indicators
	#Range: 0.0 ~ 1.0
	needleWidth = 0.1
	#Size of the arrow indicators
	#Range: 0.0 ~ 1.0
	arrowSize = 0.2
	#Draw an outline around each indicator for better visualization
	drawOutline = false
