["quantum computer"]
	#Define the maximum dimensions of the Quantum Computer Multiblock.
	#Range: 5 ~ 12
	quantumComputerMaxSize = 5
	#Define the maximum amount of multi threaders per Quantum Computer Multiblock.
	#Range: 4 ~ 16
	quantumComputerAcceleratorThreads = 8
	#Define the maximum amount of multi threaders per Quantum Computer Multiblock.
	#Range: 0 ~ 2
	quantumComputerMaxMultiThreaders = 1
	#Define the maximum amount of Data Entanglers per Quantum Computer Multiblock.
	#Range: 0 ~ 2
	quantumComputermaxDataEntanglers = 1
	#Define the multiplication factor of the multi threaders.
	#Range: 2 ~ 8
	quantumComputerMultiThreaderMultiplication = 4
	#Define the multiplication factor of the data entanglers.
	#Range: 2 ~ 8
	quantumComputerDataEntanglerMultiplication = 4
