[client]
	#Whether to display the preview of the item in the dank, disable if you have optifine
	preview = true
	#X position of preview
	#Range: -10000 ~ 10000
	preview_x = -140
	#Y position of preview
	#Range: -10000 ~ 10000
	preview_y = -25
	#Size of item text
	#Range: 0.0 ~ 1.0
	text_size = 0.5
