#Customization Settings
[customization]
	#Format that will be used to display the dimension in the tab list with the use of tokens:
	#    %d - Dimension Name*
	#    %i - Italic font
	#    %b - Bold font
	#    %u - Underline font
	#    %o - Obfuscated font
	#    %s - Strikethrough font
	#*Required (well, not technically, but it defeats the purpose without it!)
	listFormat = "%i<%d>"
	#Whether the dimension should be placed before or after the player name
	#Allowed Values: PREPEND, APPEND
	dimensionPosition = "APPEND"
	#The color to use for the dimension font if perDimColorPath is false.
	#(In the event of a modded dimension being entered, this color will be used as a fallback)
	fontColor = "DARK_AQUA"
	#Should each dimension have its own color?
	perDimColor = true
	#Global toggle for dimension aliases. Requires aliases to be set below.
	enableAliases = true

	#Per-Dimension Customization
	[customization.dimension]
		#Color to use for the Overworld
		#Allowed Values: DARK_RED, RED, GOLD, YELLOW, DARK_GREEN, GREEN, AQUA, DARK_AQUA, DARK_BLUE, BLUE, LIGHT_PURPLE, DARK_PURPLE, WHITE, GRAY, DARK_GRAY, BLACK
		#Or any custom colours defined in `customColors`
		overworldColor = "DARK_GREEN"
		#Color to use for the Nether
		#Allowed Values: DARK_RED, RED, GOLD, YELLOW, DARK_GREEN, GREEN, AQUA, DARK_AQUA, DARK_BLUE, BLUE, LIGHT_PURPLE, DARK_PURPLE, WHITE, GRAY, DARK_GRAY, BLACK
		#Or any custom colours defined in `customColors`
		netherColor = "DARK_RED"
		#Color to use for the End
		#Allowed Values: DARK_RED, RED, GOLD, YELLOW, DARK_GREEN, GREEN, AQUA, DARK_AQUA, DARK_BLUE, BLUE, LIGHT_PURPLE, DARK_PURPLE, WHITE, GRAY, DARK_GRAY, BLACK
		#Or any custom colours defined in `customColors`
		endColor = "DARK_PURPLE"

	#Chat-related Customization
	[customization.chat]
		#Should a users' current dimension be added to chat messages?
		dimInChatName = true
		#Add a hover effect in chat that will display the source of a dimension
		#Requires `dimInChatName` to be set to true
		chatDimHover = true

	#Modded Dimension Customization
	[customization.modded]
		#A list of modded dimension resource IDs and a color in the format of "modid:dim_id color"
		#For example, Twilight Forest in Gold would be "twilightforest:twilight_forest GOLD"
		#Will throw an exception if the color is not valid
		#Allowed Values: DARK_RED, RED, GOLD, YELLOW, DARK_GREEN, GREEN, AQUA, DARK_AQUA, DARK_BLUE, BLUE, LIGHT_PURPLE, DARK_PURPLE, WHITE, GRAY, DARK_GRAY, BLACK
		#Or any custom colours defined in `customColors`
		moddedDimensions = []
		#A list of aliases to use instead of the original dimension ID.
		#Uses the format 'modid:dim_id New Name'.
		#For example, to replace 'Overworld' with 'Grasslands' you would use 'minecraft:overworld Grasslands'
		#Aliases support the same tokens as `listFormat`, allowing you to make a specific dimension bold or italic or both!
		dimensionAliases = []

	#Extra Customization
	[customization.extra]
		#Custom colors can be defined here.
		#Uses the format 'COLOR_NAME #HEX' or 'COLOR_NAME r000 g000 b000'
		#If a custom color of the same name already exists the server will reject the newest one.
		#The name must be uppercase and can only contain letters and underscores.
		customColors = []
