#Show temperature debug info.
debugEnabled = false
#Show temperature values in HUD.
showTemperatureValues = true
#Require thermometer helmet enhancement to display temperature values.
requireThermometer = false
#Water loss speed when not sweating. Increase to make water loss more prevalent.
#Range: 0.01 ~ 1.0
randomWaterLoss = 0.15
#Percentage of radiation reduced when 'Radiation Protection' is added to an armor piece. For example, 0.25 with four pieces will be 100%. 1.0 will be 100% for one piece. Default gives 80% for four pieces.
#Range: 0.1 ~ 1.0
radiationReductionPercent = 0.2
