enableNoEmiMessage = true
spawnWithGuideBook = true
respawnWithGuideBook = true
disableFuelTooltips = false
disableItemTagTooltips = true
newVersionMessage = true
enableHatchPlacementOverlay = true
enableBarrelContentRendering = true
colorWaterLava = true
enableDebugCommands = false
enableBidirectionalEnergyCompat = false
enableAe2Integration = true
enableFtbQuestsIntegration = true
enableDefaultOreGenTooltips = true
datagenOnStartup = false
loadRuntimeGeneratedResources = false
removeIndustrialistTrades = false
maxDistillationTowerHeight = 9
enableInterMachineConnectedTextures = false
armorHudYPosition = 4
baseItemPipeTransfer = 16
