#O.F.Device's game server-side settings.
[server]
	#===========================================================
	#isCobblestoneFeederAvailable as boolean
	#  Whether OF C Feeders are available for devices.
	#  Default: true
	isCobblestoneFeederAvailable = true
	#===========================================================
	#enableFarmingEfficiency as boolean
	#  Whether mobs around device increase farming efficiency of device.
	#  Default: true
	enableFarmingEfficiency = true
	#===========================================================
	#accelerateProcessingSpeedByMod as boolean
	#  Whether to accelerate processing speed of device by modification.
	#         Production time       
	#        (Seconds/Product)      
	#           Mod 0  Mod 1  Mod 2 
	#    true    10.0    5.0    2.5 
	#    false   10.0   10.0   10.0 
	#  Default: true
	accelerateProcessingSpeedByMod = true
	#===========================================================
	#increaseFuelConsumptionByMod as boolean
	#  Whether to increase fuel consumption of device by modification.
	#         Fuel Consumption      
	#    Ratios of Devices to Mod 0 
	#           Mod 0  Mod 1  Mod 2 
	#    true     1      2      4   
	#    false    1      1      1   
	#  Default: true
	increaseFuelConsumptionByMod = true
