#Disabled timed crafting
disableTimedCrafting = false
#The max amount of dynamites that can be held
maxDynamites = 50
#Max drill size
drillSize = 4
#The amount of power the basic solar module will produce
basicSolarProduction = 10
#The amount of power the compact solar module will produce
compactSolarProduction = 20
#The amount of power the standard solar module will produce
standardSolarProduction = 20
#Repair item for Diamond Woodcutter
woodcutterRepairDiamond = "minecraft:diamond"
#Repair item for Hardened Woodcutter
woodcutterRepairHardened = "stevescarts:component_reinforced_metal"
#Repair item for Netherite Woodcutter
woodcutterRepairNetherite = "minecraft:netherite_ingot"
#Repair item for Iron Drill
drillRepairIron = "minecraft:iron_ingot"
#Repair item for Diamond Drill
drillRepairDiamond = "minecraft:diamond"
#Repair item for Hardened Drill
drillRepairHardened = "stevescarts:component_reinforced_metal"
#Repair item for Diamond farmer
farmerRepairDiamond = "minecraft:diamond"
#Allow carts to run with items in the tool repair slot
allowCartToRunWithRepairItems = false
#Allow fuel to be auto inserted into the cart assembler
assemblerInsertFuel = false
