[General]
	#
	############################################
	#Enable this to show the unionlib config button in the main menu
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Show Config Button" = true

[Tooltips]
	#
	############################################
	#Enable this to have the tags for certain items
	#-------------------------------------------
	#Default: false
	#-------------------------------------------
	"Boolean: Show Tags" = false
	#
	############################################
	#Sets the color of the tag tooltip
	#-------------------------------------------
	#Default: 5263440
	#-------------------------------------------
	"Tag Color" = 5263440

[Menus]
	#
	############################################
	#This determines how fast text scrolls if there is an overflow
	#Measured in ticks
	#-------------------------------------------
	#Default: 20
	#-------------------------------------------
	#Range: 1 ~ 100
	"Integer: Text Overflow Scroll Speed" = 20
	#
	############################################
	#This determines how long text will stay in an overflow before it resets
	#Measured in ticks
	#-------------------------------------------
	#Default: 40
	#-------------------------------------------
	#Range: 1 ~ 100
	"Integer: Text Overflow Reset Time" = 40
