
#Inventory sorter blacklists
[blacklists]
	#Container blacklist
	containerBlacklist = []
	#Slot type blacklist
    slotBlacklist = [
			"appeng.client.gui.me.common.ClientReadOnlySlot",
			"appeng.client.gui.me.common.RepoSlot",
			"appeng.client.gui.me.common.ClientDisplaySlot",
			"appeng.menu.slot.FakeSlot",
			"appeng.menu.slot.OptionalFakeSlot"
		]